spring.datasource.url: jdbc:h2:file:./db/flowave-h2-database
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: sa
spring.h2.console.settings.web-allow-others: true
management.endpoints.web.exposure.include: health,info
management.endpoint.health.probes.enabled: true
management.health.db.enabled: true
management.endpoint.health.group.liveness.include: livenessState
management.endpoint.health.group.readiness.include: readinessState
spring.profiles.active: eks

flowave.bpm.admin-user:
  id: demo
  password: demo